######################################################################
# Automatically generated by qmake (2.01a) ?? ???? 5 21:06:08 2012
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += . tests ui
INCLUDEPATH += . ui tests

# Input
HEADERS += desktopitem.h ui/desktop.h \
    items/itembook.h
FORMS += ui/desktop.ui
SOURCES += desktopitem.cpp main.cpp ui/desktop.cpp \
    items/itembook.cpp
